### PR TITLE
Fixed non working panic recoverer

### LINKED ISSUE #535: [BUG] - Non working panic recoverer
### Describe the bug

When panic occur in scheduled job, the whole program stops.
Even when i set
```go
gocron.SetPanicHandler(func(jobName string, recoverData interface{}) {
	fmt.Println(jobName)
	fmt.Println(recoverData)
})
```

### To Reproduce

1. Set Panic Handler
2. Invoke `Panic("test")` withing the scheduled job

### Version
Latest version: v1.31.0

### Expected behavior
Not to return exit code 2 but execute handler and keep running

### Additional context
I found fix, i will make PR with simple change in code, that works for me.

### PR DESCRIPTION
**Pull request by david-littlefarmer**
### What does this do?
Simple fix for recover panic from jobs.
I moved the recoverer part from `run()` to `runJob()`

### Which issue(s) does this PR fix/relate to?
Resolves #535 

### List any changes that modify/break current functionality
I found nothing, but all test passed, please take look at it.

### Have you included tests for your changes?
Yes, i ran `make test` and `make lint` and it all passed.

### Did you document any new/modified functionality?

- [ ] Updated `example_test.go`
- [ ] Updated `README.md`

### CODE REVIEW

**Review by JohnRoesler — APPROVED** [review]
ah! good catch. And thanks for the pr to fix it

**Comment by JohnRoesler** [comment]
Just noting this was only a bug for jobs using `SingletonMode()`

**Comment by david-littlefarmer** [comment]
Ok, i use only singleton mode, so i don't know about the others.
But so far it's working great!!! Thank you.

**Comment by VojtechVitek** [comment]
Great job, @david-littlefarmer! Thanks for the fix :)

**Pull request merged**
